POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "secret"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "sallyface_2016",
    "name": "Sal Fisher",
    "password": "glitterpony"
}